/*
NIST-developed software is provided by NIST as a public service. You may use, copy, and distribute copies of the software in any medium, provided that you keep intact this entire notice. You may improve, modify, and create derivative works of the software or any portion of the software, and you may copy and distribute such modifications or works. Modified works should carry a notice stating that you changed the software and should note the date and nature of any such change. Please explicitly acknowledge the National Institute of Standards and Technology as the source of the software.
 
NIST-developed software is expressly provided "AS IS." NIST MAKES NO WARRANTY OF ANY KIND, EXPRESS, IMPLIED, IN FACT, OR ARISING BY OPERATION OF LAW, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND DATA ACCURACY. NIST NEITHER REPRESENTS NOR WARRANTS THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED. NIST DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF THE SOFTWARE OR THE RESULTS THEREOF, INCLUDING BUT NOT LIMITED TO THE CORRECTNESS, ACCURACY, RELIABILITY, OR USEFULNESS OF THE SOFTWARE.
 
You are solely responsible for determining the appropriateness of using and distributing the software and you assume all risks associated with its use, including but not limited to the risks and costs of program errors, compliance with applicable laws, damage to or loss of data, programs or equipment, and the unavailability or interruption of operation. This software is not intended to be used in any situation where a failure could cause risk of injury or damage to property. The software developed by NIST employees is not subject to copyright protection within the United States.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "rng.h"
#include "api.h"

#include "common.h"

#define KAT_SUCCESS          0
#define KAT_FILE_OPEN_ERROR -1
#define KAT_DATA_ERROR      -3
#define KAT_CRYPTO_FAILURE  -4

char    AlgName[] = "ehtv3l1";

int
main(int argc, char** argv)
{
    char                fn_sk[32], fn_pk[32];
    FILE                *fp_sk, *fp_pk;
    unsigned char       seed[48];
    unsigned char       msg[3300];
    unsigned char       entropy_input[48];
    unsigned char       *m, *sm, *m1;
    unsigned long long  mlen, smlen, mlen1;
    unsigned char       pk[CRYPTO_PUBLICKEYBYTES], sk[CRYPTO_SECRETKEYBYTES];
    int                 ret_val;

    // Get key index to create
    unsigned int key_idx = 0;
    if (argc >= 2) {
      sscanf(argv[1], "%u", &key_idx);
      if (key_idx >= 100) {
	key_idx = 0;
      }
    }

    // Create files for the secret key, public key, and signatures.
    sprintf(fn_sk, "private.sk");
    if ( (fp_sk = fopen(fn_sk, "w")) == NULL ) {
        fprintf(stderr, "Couldn't open <%s> for write\n", fn_sk);
        return KAT_FILE_OPEN_ERROR;
    }
    sprintf(fn_pk, "public.pk");
    if ( (fp_pk = fopen(fn_pk, "w")) == NULL ) {
        fprintf(stderr, "Couldn't open <%s> for write\n", fn_pk);
        return KAT_FILE_OPEN_ERROR;
    }

    printf("Generating KAT key at index %d\n", key_idx);

    // We wish to regenerate one of the private keys found in the KATs.
    // These keys are generated by first seeding a PRNG with fixed entropy input,
    // then generating 100 seeds and messages. We call the PRNG in the same way
    // to recover the secret seed at index KEY_IDX
    for (int i=0; i<48; i++)
        entropy_input[i] = i;
    randombytes_init(entropy_input, NULL, 256);
    for (int i=0; i<100; i++) {
        randombytes(seed, 48);
        mlen = 33*(i+1);
        randombytes(msg, mlen);
	if (i == key_idx) {
	  break;
	}
    }

    // This seed is used to reseed the PRNG before generating the key.
    // We regenerate the public/private keypair from the KAT.
    randombytes_init(seed, NULL, 256);
    if ( (ret_val = crypto_sign_keypair(pk, sk)) != 0) {
      fprintf(stderr, "crypto_sign_keypair returned <%d>\n", ret_val);
      return KAT_CRYPTO_FAILURE;
    }

    // Save the secret key to a file.
    fwrite(sk, sizeof(unsigned char), CRYPTO_SECRETKEYBYTES, fp_sk);
    fclose(fp_sk);

    // Save the public key to a file.
    fwrite(pk, sizeof(unsigned char), CRYPTO_PUBLICKEYBYTES, fp_pk);
    fclose(fp_pk);
        
    return KAT_SUCCESS;
}
